# Generated by Django 4.2.18 on 2025-08-20 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_min', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subtopic')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.syllabus')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revision_type', models.CharField(choices=[('quick', 'Quick Review'), ('detailed', 'Detailed Review'), ('test', 'Practice Test')], max_length=50)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subtopic')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.syllabus')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_study_time_in_hours', models.IntegerField(help_text='Total study time in hours')),
                ('total_revision_time_in_hours', models.IntegerField(help_text='Total revision time in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revisions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_tracker.revision')),
                ('study_sessions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_tracker.studysession')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.syllabus')),
            ],
        ),
    ]
