# Generated by Django 4.2.18 on 2025-08-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressreport',
            name='user',
        ),
    ]
