# Generated by Django 4.2.18 on 2025-08-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='goal_hour',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
