# Generated by Django 4.2.18 on 2025-08-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_alter_subject_goal_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='goal_hour',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
