# Generated by Django 4.2.18 on 2025-08-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressreport',
            name='revisions',
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='study_sessions',
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='ProgressReport',
        ),
        migrations.DeleteModel(
            name='Revision',
        ),
        migrations.DeleteModel(
            name='StudySession',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Subtopic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
